### ISSUE TITLE
TypeError: argument_parser() got an unexpected keyword argument 'input_required'

### ISSUE THREAD

**Issue by Vini2** [althonos/pyrodigal-gv#5]
Hello,

I'm running`pyrodigal-gv` version 0.3.1 and I get the following error when I execute `pyrodigal-gv -h`.

```
Traceback (most recent call last):
  File "/home/mall0133/development/plables/plables/workflow/conda/809613ff587a07b3015e89229e2e5530_/bin/pyrodigal-gv", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mall0133/development/plables/plables/workflow/conda/809613ff587a07b3015e89229e2e5530_/lib/python3.12/site-packages/pyrodigal_gv/cli.py", line 27, in main
    return _main(
           ^^^^^^
  File "/home/mall0133/development/plables/plables/workflow/conda/809613ff587a07b3015e89229e2e5530_/lib/python3.12/site-packages/pyrodigal/cli.py", line 222, in main
    parser = argument_parser(input_required=stdin.isatty(), formatter_class=formatter_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument_parser() got an unexpected keyword argument 'input_required'
```

I get this error when I run using both Python 3.12.5 and 3.10.14 on a Linux machine.

Appreciate any help regarding this error.

Thanks,
Vijini

**Comment by gbouras13** [comment]
Downgrading the dependency to Pyrodgial v3.3.0 fixed this.

George

**Comment by althonos** [comment]
I had updated the code here for Pyrodigal v3.5.1 but didn't make a new release, sorry! The new release `v0.3.2` will now work with Pyrodigal `v3.5.1` or later.
